name: Publish

on:
  - push

jobs:
  test-build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build stack-algasetup image
        run: buildah bud -t okinta/stack-algasetup .

  publish:
    needs:
      - test-build-image
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: okinta/stack-algasetup
          tags: latest
